"""empty message

Revision ID: a46815b84729
Revises: 9c0fff8aa6ab
Create Date: 2024-05-02 18:35:46.778186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a46815b84729'
down_revision = '9c0fff8aa6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_record')
    with op.batch_alter_table('entryrecords', schema=None) as batch_op:
        batch_op.alter_column('studentid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('eventtype',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('phonenumber',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('seatnumber',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['seatnumber'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('seatnumber',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('phonenumber',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               nullable=True)

    with op.batch_alter_table('entryrecords', schema=None) as batch_op:
        batch_op.alter_column('eventtype',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('studentid',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('entry_record',
    sa.Column('record_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.studentid'], name='fk_entry_record_student_id'),
    sa.PrimaryKeyConstraint('record_id', name='pk_entry_record')
    )
    # ### end Alembic commands ###
